MobileNativeFoundation/bluepill

- Bluepill-cli/Bluepill-cli.xcodeproj/project.pbxproj
- Bluepill-cli/bluepill-cli-release.xcconfig
- Bluepill-cli/bluepill-cli.xcconfig
- Bluepill-runner/Bluepill.xcodeproj/project.pbxproj
- Bluepill-runner/bluepill.xcconfig
- Bluepill.xcworkspace/contents.xcworkspacedata
- Configurations/common.xcconfig
Get ready for brew upload. Added settings to make installation easier.
> Abstract common settings for bluepill and bp 

- Bluepill-cli/Bluepill-cli/Simulator/SimulatorMonitor.m
- Bluepill-runner/Bluepill-runner/BPApp.m
- Bluepill-runner/Bluepill-runner/BPPacker.h
- Bluepill-runner/Bluepill-runner/BPPacker.m
- Bluepill-runner/Bluepill-runner/BPRunner.m
- Bluepill-runner/BluepillRunnerTests/BPRunnerTests.m
Fix #9 and #17 
Also, only send the kill signal to valid PIDs.
> Fix confusing errors

- Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
- Bluepill-cli/Bluepill-cli/Simulator/SimulatorRunner.h
- Bluepill-cli/Bluepill-cli/Simulator/SimulatorRunner.m
- Bluepill-runner/Bluepill-runner/BPRunner.m
> Small bug fixes

- Bluepill-gui/Bluepill-gui.xcodeproj/project.pbxproj
- Bluepill-gui/Bluepill-gui/BPConstants.h
- Bluepill-gui/Bluepill-gui/CheckboxHeader.h
- Bluepill-gui/Bluepill-gui/CheckboxHeader.m
- Bluepill-gui/Bluepill-gui/ConfigView.h
- Bluepill-gui/Bluepill-gui/ConfigView.m
- Bluepill-gui/Bluepill-gui/MainWindowController.xib
- Bluepill-gui/Bluepill-gui/OtherView.h
- Bluepill-gui/Bluepill-gui/OtherView.m
- Bluepill-gui/Bluepill-gui/Utils/BPPrefs.h
- Bluepill-gui/Bluepill-gui/Utils/BPPrefs.m
- Bluepill-runner/Bluepill.xcodeproj/xcshareddata/xcschemes/bluepill.xcscheme
This change brings in the missing files from when the project was pushed to github and allows the bluepill-gui project to compile.
> Bring in pre-Github changes for a compiling GUI.

- Bluepill-cli/BPInstanceTests/BPCLITests.m
- Source/Shared/BPConfiguration.m
#89 
Add BP_MASTER to test-bundle-path so it doesn't fail out when the parameter is passed
> #89 Add BP_MASTER to test_bundle_path for fix its use

- .travis.yml
- Bluepill-cli/BPInstanceTests/BluepillTests.m
- Bluepill-cli/Bluepill-cli.xcodeproj/xcshareddata/xcschemes/BPInstanceTests1.xcscheme
- Bluepill-cli/Bluepill-cli.xcodeproj/xcshareddata/xcschemes/BPInstanceTests2.xcscheme
- Bluepill-cli/Bluepill-cli.xcodeproj/xcshareddata/xcschemes/BPInstanceTests3.xcscheme
- Bluepill-cli/Bluepill-cli/Simulator/SimulatorHelper.m
- Bluepill-runner/Bluepill-runner/main.m
- Bluepill-runner/Bluepill.xcodeproj/xcshareddata/xcschemes/BPIntegrationTests.xcscheme
- scripts/bluepill.sh
Not as elegant as I would like but better than not passing at all.
> An attempt to fix travis builds

- .travis.yml
- Bluepill-cli/Bluepill-cli.xcodeproj/project.pbxproj
- Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
- Bluepill-cli/Bluepill-cli/Bluepill/Connections/BPTestBundleConnection.m
- Bluepill-cli/Bluepill-cli/Bluepill/Connections/BPTestDaemonConnection.m
- Source/Shared/BPConstants.h
> Xcode-8.3 support

- Bluepill-cli/BPInstanceTests/Resource Files/testScheme.xcscheme
- Source/Shared/BPUtils.m
#134 
Only add launch args and environment variables if they are enabled in the scheme
> #134: Don't Use Disabled Launch Args and Env Variables

- Bluepill-cli/BPInstanceTests/BluepillTests.m
- Bluepill-runner/Bluepill-runner/BPPacker.m
- Bluepill-runner/BluepillRunnerTests/BPRunnerTests.m
> Fix Include cannot use testsuite to test only tests in that suite #138

- Bluepill-runner/Bluepill-runner/BPPacker.m
- Bluepill-runner/BluepillRunnerTests/BPRunnerTests.m
This adds support to provide just the testsuite name for the include or exclude option in order to include all test cases in the suite, or to exclude all test cases in that suite.
Addresses Issue #138
> Support option to include/exclude all tests in a given test-suite

- Bluepill-cli/BPInstanceTests/BluepillTests.m
- Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
- Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
- Bluepill-cli/Bluepill-cli/main.m
- Source/Shared/BPConfiguration.m
> First cut at cleaning up debugging.

- Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
- Source/Shared/BPUtils.m
fix Bluepill is blocked when reading tests from xctest file #167 [https://github.com/linkedin/bluepill/issues/167](url)
> fix NSTask waitUntilExit hanging

- Bluepill-cli/Bluepill-cli/Bluepill/Reporters/BPTreeParser.m
- Bluepill-runner/Bluepill-runner/BPRunner.m
- Bluepill-runner/BluepillRunnerTests/BPIntegrationTests.m
- Source/Shared/BPUtils.m
- Source/Shared/BPXCTestFile.m
1) Fixed a few nil pointer issues, 2) Fix static linking issue
> Merge a few crash tickets fix and static linking fix

- Bluepill-cli/BPInstanceTests/BPTreeParserTests.m
- Bluepill-cli/BPInstanceTests/Resource Files/uitest-failed.log
- Bluepill-cli/Bluepill-cli.xcodeproj/project.pbxproj
- Bluepill-cli/Bluepill-cli/Bluepill/Reporters/BPTreeParser.h
- Bluepill-cli/Bluepill-cli/Bluepill/Reporters/BPTreeParser.m
Potential fix for #200. Ideally someone else should validate that this actually works 🤣
> Fix a parsing failure for UI Tests (Issue #200)

- README.md
> Intetgrate -> Integrate

- README.md
Created new fastlane plugin that supports XCode 9,2 and other featured needed for my work.
> Adding new fastlane plugin description

- .circleci/config.yml
- README.md
- Source/Shared/BPConstants.h
https://github.com/linkedin/bluepill/issues/261
> Add support for Xcode 9.4

- Bluepill-cli/Bluepill-cli.xcodeproj/project.pbxproj
Fix an issue for bp loading BluepillLib.framework
> update bp search path

- Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
Remove unnecessary app launch environment variable
> update app launch environment

- Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
Establish daemon connection first to avoid XCTIDEConnectionTimeout
> Daemon connection first

- Source/Shared/BPXCTestFile.m
This is also to enable bluepill to work with the xctestrun format in xctestrunner. Xctestrunner generate xctestrun file with the following format:
TestBundlePath: \_\_TESTROOT__/example.app/PlugIns/exampleUnitTests.xctest
TestHostPath: \_\_TESTROOT__/example.app
> remove xcode9beta5 workaround

- Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
In the definition of:
```
-[BPSimulator installApplicationWithHost:withError:error]
```
The impl had a type mismatch error, which caused the address of the
error to be treated the actual error.
> Fix error usage in BPSimulator

- Bluepill-cli/Bluepill-cli/Bluepill/Helpers/BPHandler.m
- Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
- Bluepill-runner/BluepillRunnerTests/BPIntegrationTests.m
It was broken before, this fixes it and adds a test to make sure it stays working.
> Fix clone-simulator feature

- README.md
Update README.md to use Azure Pipelines build status badge
> Update README.md to use Azure Pipelines badge

- bptestrunner/ios_bluepill_test_runner.bzl
> Clean up starlark code

- .github/workflows/main.yml
Automate releases using https://github.com/marketplace/actions/gh-release action. 
Deprecates https://github.com/linkedin/bluepill/pull/359
> CD integration with GitHub Actions

- scripts/man.py
Small fixes to the man page and new tag to test automated releases.
> Small fixes to man page

- bluepill/bluepill.xcodeproj/xcshareddata/xcschemes/bluepill-tests.xcscheme
- bp/bp.xcodeproj/xcshareddata/xcschemes/bp-tests.xcscheme
Manually balanced tests between 2 machines
> Cleaned up test schemes.

- .github/workflows/CI-release.yml
- Bluepill.podspec
As a part of CI-release, we also publish a version to Cocoapods so consumers
can use Pod 'Bluepill'
> Pod release

- bp/src/Bluepill.m
In `Bluepill.m`, multiple things will increment retry count: `retry`, `recover`, and `proceed`.
I noticed a scenario where when the test consistently crashed the app, bluepill would continually retry.
```
{48691} 20200407.220529 [  INFO  ] (BP-1) Retry count: 29
{48691} 20200407.220529 [  INFO  ] (BP-1) Proceeding to next test
{48691} 20200407.220529 [  INFO  ] (BP-1) Running Tests. Attempt Number 30.
{48691} 20200407.220529 [  INFO  ] (BP-1) [Attempt 30] Create Simulator
{48691} 20200407.220530 [  INFO  ] (BP-1) Booting a simulator without launching Simulator app
```
The  `--error-retries` flag was set to 2.
I believe this happened because the retry count was incremented past 2 without being checked against the error retries, and resulted in an infinite loop of crashes and proceeds. …
> Make retry checks more resilient to prevent infinite retries

- .github/workflows/PR.yml
- .github/workflows/master.yml
- .github/workflows/release.yml
- README.md
- bp/src/BPConstants.h
Adding Xcode 11.4 support. 
Ref: https://github.com/linkedin/bluepill/issues/440
> Xcode 11.4 support

- .github/workflows/PR.yml
- .github/workflows/master.yml
- .github/workflows/release.yml
- README.md
- bp/src/BPConstants.h
Adding Xcode 11.5 support.
Ref: Issue https://github.com/linkedin/bluepill/issues/445
> Xcode 11.5 support

- .github/workflows/PR.yml
- .github/workflows/master.yml
- .github/workflows/release.yml
- BPSampleApp/BPSampleAppHangingTests/BPSampleAppHangingTests.m
- README.md
- bluepill/tests/BPPackerTests.m
- bp/bp.xcodeproj/xcshareddata/xcschemes/bp-tests.xcscheme
- bp/src/BPConfiguration.h
- bp/src/BPConfiguration.m
- bp/src/BPConstants.h
- bp/src/BPExitStatus.h
- bp/src/BPExitStatus.m
- bp/src/BPSimulator.m
- bp/src/BPStats.m
- bp/src/BPUtils.m
- bp/src/Bluepill.m
- bp/src/SimulatorMonitor.m
- bp/tests/BPUtilsTests.m
- bp/tests/BluepillTests.m
- bp/tests/Resource Files/hanging_tests.xml
LinkedIn needs a Bluepill release with Xcode 11.5 support without exit status code fixes for app crashes. So, this revert commit is to do a minor release for the same.
> Release with Xcode 11.5 support and without app crash exit code fixes

- bluepill/src/BPApp.m
- bp/src/BPConfiguration.m
- bp/src/Bluepill.m
- bp/tests/Resource Files/testConfig-busted.json
* Avoid NPE when appBundlePath is nil in BPConfiguration
* Minor logging changes
* Better error handling
> Fixing minor issues and doing some minor refactoring/clean-up

- .github/workflows/PR.yml
- .github/workflows/master.yml
- .github/workflows/release.yml
- README.md
- bluepill/tests/BPIntegrationTests.m
- bp/src/BPConstants.h
- bp/src/SimulatorHelper.m
- bp/tests/Resource Files/BPAppNegativeTests-results.xml
- bp/tests/SimulatorHelperTests.m
- scripts/bluepill.sh
Adding Xcode 12.0 support (Ref: Issue https://github.com/linkedin/bluepill/issues/453)
\cc @ob @chenxiao0228 @oliverhu @RainNapper @jerrymarino
> Xcode 12.0 support

- .github/workflows/PR.yml
- .github/workflows/master.yml
- .github/workflows/release.yml
- README.md
- bluepill/tests/BPIntegrationTests.m
- bp/src/BPConstants.h
> Xcode 12.2 Support

- .github/workflows/PR.yml
- .github/workflows/master.yml
- .github/workflows/release.yml
- README.md
- bp/src/BPConstants.h
> Xcode 12.4 support

- README.md
- bluepill/tests/BPIntegrationTests.m
- bp/src/BPConfiguration.h
- bp/src/BPConfiguration.m
- bp/src/BPTMDRunnerConnection.m
Accidentally closed this PR by deleting the branch
https://github.com/MobileNativeFoundation/bluepill/pull/461/files
> Delete videos of passed tests, add flag to retain

- README.md
I noticed a small tense error while reading the README.
This project looks amazing!
> README: Fix tense

- .github/workflows/PR.yml
- README.md
- bp/src/BPConstants.h
Fixes #516 
Signed-off-by: Oscar Bonilla <6f6231@gmail.com>
> Bump to Xcode 13.1

- .github/workflows/PR.yml
- .github/workflows/master.yml
- .github/workflows/release.yml
- README.md
- bp/bp.xcodeproj/project.pbxproj
- bp/src/BPConstants.h
necessary changes for Xcode 14 support.
> Add xcode 14 support

- bptestrunner/bluepill_batch_test_runner.template.sh
cherry-pick https://github.com/MobileNativeFoundation/bluepill/pull/553 to xcode-14.0 branch
> Expand $TEST_UNDECLARED_OUTPUTS_DIR  when running test from bazel (#553)
