Bluepill-cli/BPInstanceTests/BluepillTests.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorHelper.m
README.md
Source/Shared/BPConfiguration.m

This prioritizes skipped tests over included tests.

(Closes #29) Allow include tests and skip tests to be set at the same time.

---

Bluepill-cli/Bluepill-cli/Simulator/SimulatorMonitor.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorRunner.m

- Ensure the runner remains around for the lifetime of the launch application block
- Add more logging around killing the app in the simulator in case the above fix doesn't do anything

Try to handle the hang-after-timeout issue #38

---

Bluepill-runner/Bluepill-runner/BPPacker.h
Bluepill-runner/Bluepill-runner/BPPacker.m
Bluepill-runner/Bluepill-runner/BPRunner.m
Bluepill-runner/BluepillRunnerTests/BPRunnerTests.m

If a bundle had 100 tests and you specify the first 10 with the `include` option on 5 simulators, instead of running 2 tests on each simulator, it would run all 10 on one simulator, then start up and run 0 tests on the other 4. This fixes that.

Correctly partition tests when only testing a subset.

---

README.md

**1). Fix xcode-path command line argument in the documentation**
It’s confusing as current xcode-path argument conflicts with the existing «exclude» flag. It also differs from what the ./bluepill -h says.
**2). Fix typo in README ("Select" instead of "Selet")**

Fix xcode-path command line argument in the documentation

---

Bluepill-runner/Bluepill-runner/BPApp.h
Bluepill-runner/Bluepill-runner/BPApp.m
Bluepill-runner/Bluepill-runner/main.m
Source/Shared/BPConfiguration.h
Source/Shared/BPConfiguration.m
Source/Shared/BPTestClass.m
Source/Shared/BPXCTestFile.m

Also changed test case output format to TestClassName/TestCaseName.

(Closes #35) Make verbose mode default when listing tests.

---

Bluepill-cli/Bluepill-cli/Simulator/SimulatorMonitor.m

We can't send `SIGTERM` to the app and expect it to die as `SIGTERM` can be ignored. If a test times out, kill the app using `SIGKILL` which is non-blockable and non-ignorable.

Kill the app with prejudice

---

Bluepill-runner/Bluepill-runner/BPApp.m

This PR is to the ui_test branch to fix an issue in that branch.  Corresponding issue is #16 
For the ui tests, the test bundles were being added as one array to allTestBundles instead of individual xctFiles.  This caused an exception in BPPacker where it was expecting a BPXCTestFile but instead had an array.

Fix UI test bundles being and array of array instead of array of xctFile

---

Bluepill-cli/Bluepill-cli/Simulator/SimulatorMonitor.m

#90 
Remove hardcoded test startup timeout so it uses the stuck timeout parameter

#90 Remove hardcoded timeout for test startup

---

Bluepill-runner/Bluepill-runner/BPApp.m

This was introduced in the UI Test PR (#88) and was causing bluepill to exit with `ERROR: (null)`.

error wasn't being dereferenced

---

Bluepill-cli/BPInstanceTests/BPCLITests.m
Bluepill-cli/BPInstanceTests/BPConfigurationTests.m
Bluepill-cli/BPInstanceTests/BluepillTests.m
Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
Bluepill-runner/BluepillRunnerTests/BPIntegrationTests.m
Bluepill-runner/BluepillRunnerTests/BPRunnerTests.m
Source/Shared/BPConfiguration.h
Source/Shared/BPConfiguration.m

NSNumber options in BPConfiguration were getting set as NSStrings when set from the command line.
This was working for most options because intValue or integerValue works on both NSString and NSNumber.
Added a BP_INTEGER option type so that integers are explicitly converted to NSNumber.

Fix for failtureTolerance (-f) option not working from the command line

---

Bluepill-cli/BPInstanceTests/SimulatorHelperTests.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorHelper.m

The environment variables to write coverage data weren't getting set. This meant the coverage data wasn't being written even if a target was built with code coverage enabled.
llvm-profdata needs to be called afterwards to merge the separate profraw files into a single coverage file:
`xcrun llvm-profdata merge -sparse output-dir/**/*.profraw -o Coverage.profdata`
(Thanks to https://github.com/plu/pxctest/issues/13 for the correct variables to set)

Add support for coverage data

---

Bluepill-cli/BPInstanceTests/BPTestHelper.m
Bluepill-cli/BPInstanceTests/SimulatorHelperTests.m
Bluepill-runner/Bluepill-runner/BPApp.h
Bluepill-runner/Bluepill-runner/BPApp.m
Bluepill-runner/BluepillRunnerTests/BPRunnerTests.m

This PR fixes that test bundle can't find on Mac OS Extended (Case-sensitive, Journaled) filesystem.
Xcode generate test bundles into "AppBundle/Plug<strong>I</strong>ns" after performing "Build for tests".
Original source is hard coded "Plugins"

Fix "PlugIns" directory can not be found on case-sensitive file system

---

Bluepill-cli/BPInstanceTests/BPUtilsTests.m
Bluepill-cli/BPInstanceTests/Resource Files/testScheme.xcscheme
Source/Shared/BPUtils.m

#118 
This updates bluepill to read the test action env variables in addition to the launch action.  Updated the unit test to test this.
Should be reviewed if this would have negative impact on testing other than xctest.

#118: Read environment variables for test action

---

BPSampleApp/BPSampleAppHangingTests/BPSampleAppHangingTests.m
Bluepill-cli/Bluepill-cli.xcodeproj/xcshareddata/xcschemes/BPInstanceTests1.xcscheme
Bluepill-cli/Bluepill-cli.xcodeproj/xcshareddata/xcschemes/BPInstanceTests2.xcscheme
Bluepill-cli/Bluepill-cli.xcodeproj/xcshareddata/xcschemes/BPInstanceTests3.xcscheme
Bluepill-cli/Bluepill-cli/Bluepill/Connections/BPTestBundleConnection.m
Bluepill-cli/Bluepill-cli/Bluepill/Reporters/BPTreeParser.m
Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorHelper.m
Bluepill-runner/Bluepill.xcodeproj/xcshareddata/xcschemes/BPIntegrationTests.xcscheme

We've seen certain cases (root cause undetermined) where a test case will hang while only printing new lines (sometimes millions of them). 
While the test case might be the culprit, it seems easy enough to not count empty new lines as output in bluepill and treat this kind of busy-hanging as a test hanging.

Fix a bp hang when a test case just prints new lines

---

BPSampleApp/BPSampleAppHangingTests/BPSampleAppHangingTests.m
Bluepill-cli/Bluepill-cli/Bluepill/Reporters/BPTreeParser.m

A more careful examination illustrated that the problem wasn't with a test that loops indefinitely. It turns out that we weren't error checking the UTF-8 decoding of the buffer and if the data happened to be cut in the middle of a UTF-8 char, you'd get an error decoding it and the loop would never finish.
This isn't the Right Fix(tm), but it's better than what's in there... the right fix would be to read the data in chunks without interpreting anything until we get to the `\n`, then convert the full line to an NSstring and move the remaining data to another buffer. 
We're pushing this out though because it's a quick workaround for a serious bug.

Better fix for app hanging by printing a bunch of new lines

---

Bluepill-runner/Bluepill-runner/BPPacker.m
Bluepill-runner/BluepillRunnerTests/BPRunnerTests.m

This fixes an issue where all non-skipped tests are run on the one simulator by balancing the desired tests between different simulators. Before, only one bundle got the desired tests if the number of skipped tests was large.
Issue: https://github.com/linkedin/bluepill/issues/145

Fix balancing of tests to run after excluding skipped tests

---

Source/Shared/BPXCTestFile.m

Updates the `UITargetAppPath` so that it gets the expanded path

fix issue with app-to-be-tested not being set

---

Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m

fix this [https://github.com/linkedin/bluepill/issues/169](https://github.com/linkedin/bluepill/issues/169)

CommandLineArguments in xctestrun file can't be set in simulator

---

Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
Source/Shared/BPConfiguration.m

We were doing this fix in the parsing of config files stage, but this seems to be needed
for every run of the app so it fits better in the launchApp stage.
I think this is needed because of what I found while investigating #179 (namely [this](https://github.com/linkedin/bluepill/issues/179#issuecomment-314189528)).

Move the code that appends commandLineArguments to bp

---

Bluepill-cli/BPInstanceTests/BluepillTests.m
Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorMonitor.m
README.md

With this change, we have 3 majors flow for the rerun logic.
BPExitStatusTestsFailed -> Retry, require failureTolerance > 0
Tooling failure(BPExitStatusSimulatorCreationFailed,BPExitStatusSimulatorCrashed,BPExitStatusInstallAppFailed,BPExitStatusUninstallAppFailed,BPExitStatusLaunchAppFailed) -> recover from scratch, even if failureTolerance=0. 
BPExitStatusTestTimeout/BPExitStatusAppCrashed -> proceed, even if failureTolerance=0
This will fix one issue which is 'if failureTolerance=0 and tooling failure happens(simulator creation failed/crash), then test will stop and return as fail'. With this change, it will try to recover the tooling failure and rerun it.

Recover from scratch if there is tooling failure

---

Bluepill-cli/Bluepill-cli/Bluepill/Connections/BPTestBundleConnection.m

`_XCT_testMethod:ofClass:didMeasureMetric:file:line:` should return nil instead of calling `handleUnimplementedXCTRequest:`
This also fixes `unknownMessageForSelector:` crashing, which was making reading the diagnostics a bit trickier because bp was crashing instead of printing the assertion.
Fixes #201.

Fixed crash when encountering a test with measureBlock:

---

Bluepill-cli/Bluepill-cli/Simulator/SimulatorHelper.m

This solves the problem for me, but I suspect that sometimes this parameter should be NO. (For pre-9 versions of Xcode, maybe?). Feedback is welcomed.

Simple fix for https://github.com/linkedin/bluepill/issues/199

---

Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
Bluepill-cli/Bluepill-cli/Bluepill/Connections/BPTestBundleConnection.m
Bluepill-cli/Bluepill-cli/Bluepill/Connections/BPTestDaemonConnection.m
Bluepill-cli/Bluepill-cli/Bluepill/Reporters/BPExitStatus.h
Bluepill-cli/Bluepill-cli/Bluepill/Reporters/BPTreeParser.m
Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.h
Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorHelper.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorMonitor.h
Bluepill-cli/Bluepill-cli/Simulator/SimulatorMonitor.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorScreenshotService.m
Bluepill-cli/Bluepill-cli/main.m
Bluepill-runner/Bluepill-runner/BPRunner.m
Bluepill-runner/BluepillRunnerTests/BPIntegrationTests.m
Source/Shared/BPUtils.h
Source/Shared/BPXCTestFile.m

This is a fun one... xcodebuild build-for-testing adds the derivedData directory  to the DYLD_FRAMEWORK_PATH and DYLD_LIBRARY_PATH environment  variables so that if a framework is built but not added to the app bundle, the app will still load in the simulator. Obviously, once the app is installed in an actual device it won't load.
This commit clears up those variables so that the only frameworks available to the app are the ones bundled with it. It also fixes the logic for detecting a crashed application which was wrong (if the app crashed early enough, like when loading dynamic libraries).
Also clean up all the info message format strings by adding the proper compiler directives.

Fix a bug where we were loading frameworks from the build directory

---

README.md

Hey,
as I tried building Bluepill from source I noticed that the path mentioned in the README file isn't valid (anymore). As `bluepill.sh` is located in the `scripts` folder, but needs to be run from the root-directory the path should include the folder name (as it does already for the test changes against bluepill part).

README: Fix script path on how to build Bluepill from source

---

Bluepill-cli/BPInstanceTests/BluepillTests.m
Bluepill-cli/BPInstanceTests/Resource Files/hanging_tests.xml
Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorMonitor.h
Bluepill-cli/Bluepill-cli/Simulator/SimulatorMonitor.m
circle.yml
scripts/bluepill.sh

SimulatorMonitor was trying to keep track of multiple things using a
single state variable which caused a bunch of problems. One of them
was a race between when the app finishes (the process exits) and the
output parser has finished parsing. We use a FIFO for grabbing the
output so it's buffered. This means that after the app has finished,
the parser is still parsing for short while (how short depends on how
fast the machine is).

Simplify SimulatorMonitor and fix races

---

BPSampleApp/BPSampleApp.xcodeproj/project.pbxproj
BPSampleApp/BPSampleAppTests/BPSampleAppSwiftTests.swift
BPSampleApp/BPSampleAppTests/BPSampleAppTests-Bridging-Header.h
Bluepill-cli/BPInstanceTests/BPConfigurationTests.m
Bluepill-cli/BPInstanceTests/BPUtilsTests.m
Bluepill-cli/BPInstanceTests/Resource Files/testConfig.json
Bluepill-runner/BluepillRunnerTests/BPPackerTests.m
Source/Shared/BPConfiguration.m
Source/Shared/BPUtils.h
Source/Shared/BPUtils.m
Source/Shared/BPXCTestFile.m

Test names extracted from the xctestrun file have parantheses at the end which also require specific params to have the same. Adding a regex pattern to trim the test name.

Removing trailing parantheses from test names

---

Bluepill-cli/BPInstanceTests/BluepillTests.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorMonitor.m

Xcode 9.4 caused the two flaky app hanging tests fail. This commit is to fix the flakiness.

Fix app hanging tests flakiness

---

Bluepill-runner/Bluepill-runner/BPReportCollector.m

When there is a BP worker did not do any test, it will result in empy xml file. In that case, it will result in exmpy final test report. This pull request is to fix this issue.

Fix Test Report Issue

---

Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m

Xcode 10 is slower to establish control session. This is to avoid "timed out failure with IDE session ready for test plan"

extend XCTIDEConnectionTimeout

---

Bluepill-cli/BPInstanceTests/BPTestHelper.h
Bluepill-cli/BPInstanceTests/BPTestHelper.m
Bluepill-cli/BPInstanceTests/BluepillTests.m
Bluepill-cli/BPInstanceTests/Resource Files/script.sh
Bluepill-cli/BPInstanceTests/Resource Files/test-script.sh
Bluepill-cli/Bluepill-cli.xcodeproj/project.pbxproj
Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.h
Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
Source/Shared/BPConfiguration.h
Source/Shared/BPConfiguration.m

This adds a way to run a script after a simulator is booted, but before tests are run. One reason to use this is to install certificates to integrate with mitmproxy (per #194)

Add --script-file-path to run a user script

---

Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
Source/Shared/BPConfiguration.h
Source/Shared/BPConfiguration.m

`handler.onTimeout` is not working properly to retry lanuch app because it does not terminate the current thread. If it retries while the original thread succeeds with launch, it will cause wrong sim device status as there are two threads that are trying to continue to run test.

Start a fresh retry after launch app failed

---

Bluepill-runner/Bluepill-runner/BPRunner.m
Source/Shared/BPConfiguration.h
Source/Shared/BPConfiguration.m

Added a configuration option "keep-individual-test-reports" to keep the files when needed.

Delete individual test reports by default

---

BPSampleApp/BPAppNegativeTests/BPAppNegativeTests.m
BPSampleApp/BPSampleApp.xcodeproj/xcshareddata/xcschemes/BPSampleApp.xcscheme
Bluepill-cli/BPInstanceTests/BluepillTests.m
Bluepill-cli/BPInstanceTests/Resource Files/BPAppNegativeTests-results.xml
Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
Bluepill-runner/BluepillRunnerTests/BPIntegrationTests.m
Bluepill-runner/BluepillRunnerTests/BPPackerTests.m
Source/Shared/BPConfiguration.m
Source/Shared/BPUtils.m
scripts/bluepill.sh

Remove pipe for communication between app and bp
This fixes a bug where if the output of a failed test was too big, then bp would deadlock with the app and think the app was hung. It would essentially turn a test failure into a timeout.
Rather than worry about the corners of properly synchronizing over a named pipe, I just have the app log to a file and wire the parser to read from that file.
This was very apparent when using Earl Grey because the failures include full stack traces and UI hierarchy dumps.
This PR also includes two other small bug fixes:
1. verbose logging wasn't working (`-v`) options
2. The `skipTestIdentifiers` property in the `xctestrun` file wasn't being honored.

Fix a failure where a failing test would hang (fixes Earl Grey tests)

---

Bluepill-runner/Bluepill-runner/BPReportCollector.m
Bluepill-runner/BluepillRunnerTests/BPReportCollectorTests.m
Bluepill-runner/BluepillRunnerTests/simulator/3/result3.xml
Bluepill-runner/BluepillRunnerTests/simulator/4/result4.xml

This is a followup to #324, the order in which the tests were run wasn't being preserved.

Preserve the order in which tests were run

---

azure-pipelines.yml
scripts/bluepill.sh

This is a sample execution
https://dev.azure.com/lnkd-oss/Bluepill/_build/results?buildId=37

Introduce builds and tests using Azure DevOps

---

bluepill/src/BPRunner.m
bp/src/BPConfiguration.m

Two minor fixes:
1. Fewer simulators can be used if the number of bundles is less than the number of simulators.
2. There cannot be fewer than one simulator. Throw an error in case of a bad configuration (before it could possibly result in a divide-by-zero exception [here](https://github.com/linkedin/bluepill/blob/master/bluepill/src/BPPacker.m#L50)).
\cc @ob

Validating the numSims configuration and adjusting it when needed

---

BPSampleApp/BPSampleAppCrashingTests/BPSampleAppCrashingTests.m
bp/src/BPConfiguration.h
bp/src/BPConfiguration.m
bp/src/BPSimulator.m
bp/src/Bluepill.m
bp/tests/BluepillTests.m

When a test crashed and then passed in a retry, bp was still
reporting the crash in the exit status. This fixes it.

Fix wrong exit status

---

WORKSPACE
bptestrunner/bluepill_test_runner.template.sh
bptestrunner/ios_bluepill_test_runner.bzl
bptestrunner/main.py

Also, bump rules_apple and subpar to latest versions

Allow passing a config file to bptestrunner

---

bluepill/src/main.m
bp/src/BPUtils.h
bp/src/BPUtils.m
bp/src/main.m

Pass argc and argv and then rewrite argv so the first argument uses the full path to the executable.
Otherwise running bluepill from a shell will fail because `argv[0]` will be just `bluepill` rather than the full path to the executable.
Introduced in #327.

Fixed setupWeakLinking asserting if bluepill is launched without a full executable path

---

bptestrunner/main.py

I just realized we had the precedence wrong here. The Bazel rule needs to be able to override the values in the configuration file (much like the command line arguments) instead of the other way around.

bptestrunner: Reverse precendence of configuration

---

bptestrunner/main.py

With [this Python toolchain cleanup](https://github.com/bazelbuild/bazel/issues/7899) in Bazel, it's better if the script is agnostic about which version of python is being used.

Make bptestrunner work with python 2 and python 3

---

.github/workflows/main.yml

Given the issues with GH connection and ADO, let's see if we can use GH Actions instead. This version only tests and builds - I'll add auto-release automation later once this is stable (to effectively do what  https://github.com/linkedin/bluepill/pull/359 is trying to accomplish)

First stab at using GH Actions for CI

---

scripts/bluepill.sh
scripts/bpversion.sh

GitHub actions doesn't seem to trigger releases on annotated tags, so add the --tags flag to the calls to git describe so that it honors lightweight tags.

Use lightweight tags in git describe

---

.gitignore
BPSampleApp/BPSampleApp.xcodeproj/xcshareddata/xcschemes/BPSampleApp.xcscheme
bluepill/bluepill.xcodeproj/xcshareddata/xcschemes/bluepill-tests.xcscheme
bluepill/bluepill.xcodeproj/xcshareddata/xcschemes/bluepill.xcscheme
bp/bp.xcodeproj/xcshareddata/xcschemes/bp-tests.xcscheme
bp/bp.xcodeproj/xcshareddata/xcschemes/bp.xcscheme

Fixing the Xcode project set-up that was causing some tests to fail along with some other minor Xcode project-related changes.
Not sure how this issue got in, in the first place! Please review the changes.
\cc @ob @jmkk @chenxiao0228

Fixing xcode project set-up that was causing some tests to fail

---

bluepill/src/BPApp.m
bluepill/src/BPPacker.m
bluepill/src/BPReportCollector.m
bluepill/src/BPRunner.h
bluepill/src/BPRunner.m
bluepill/src/main.m
bluepill/tests/BPAppTests.m
bluepill/tests/BPIntegrationTests.m
bluepill/tests/BPPackerTests.m
bp/src/BPConfiguration.m
bp/src/BPConstants.h
bp/src/BPSimulator.m
bp/src/BPUtils.h
bp/src/BPUtils.m
bp/src/BPXCTestFile.h
bp/src/BPXCTestFile.m
bp/src/Bluepill.m
bp/src/SimulatorHelper.h

**TL;DR** Rebasing changes from https://github.com/linkedin/bluepill/pull/378 to be merged into master
**Major change:** Do not look for bp binary on PATH and simply fail if it is not found adjacent to the bluepill binary.
Also did some refactoring, cleanup and improvements like...
1. Moved a helper method to utils
2. Enhancing error messages and better error handling
3. Fixing asserts in tests
4. Renaming variables
**P.S:** Works best if pushed after https://github.com/linkedin/bluepill/pull/379
\cc @ob @jmkk Please review.

[Master] Some refactoring and fail if bp binary is not found adjacent to bluepill binary

---

.gitignore
BPSampleApp/BPSampleApp.xcodeproj/xcshareddata/xcschemes/BPSampleApp.xcscheme
Bluepill-cli/Bluepill-cli/Bluepill/Bluepill.m
Bluepill-cli/Bluepill-cli/Simulator/BPSimulator.m
Bluepill-cli/Bluepill-cli/Simulator/SimulatorHelper.h
Bluepill-runner/Bluepill-runner/BPApp.m
Bluepill-runner/Bluepill-runner/BPPacker.m
Bluepill-runner/Bluepill-runner/BPReportCollector.m
Bluepill-runner/Bluepill-runner/BPRunner.h
Bluepill-runner/Bluepill-runner/BPRunner.m
Bluepill-runner/Bluepill-runner/main.m
Bluepill-runner/BluepillRunnerTests/BPAppTests.m
Bluepill-runner/BluepillRunnerTests/BPIntegrationTests.m
Bluepill-runner/BluepillRunnerTests/BPPackerTests.m
Bluepill-runner/bluepill.xcodeproj/xcshareddata/xcschemes/bluepill-tests.xcscheme
Bluepill-runner/bluepill.xcodeproj/xcshareddata/xcschemes/bluepill.xcscheme
Source/Shared/BPConfiguration.m
Source/Shared/BPConstants.h
Source/Shared/BPUtils.h
Source/Shared/BPUtils.m
Source/Shared/BPXCTestFile.h
Source/Shared/BPXCTestFile.m

Do not look for `bp` binary on `PATH` and simply fail if it is not found adjacent to the `bluepill` binary.
Also did some refactoring, cleanup and improvements like...
1. Moved a helper method to utils
2. Enhancing error messages and better error handling
3. Fixing asserts in tests
4. Renaming variables
\cc @ob @jmkk Please review.

Fail if bp binary is not found adjacent to bluepill and also some refactoring

---

.github/workflows/CI-PR.yml

Removing a limitation of running tests only on PRs based on the `master` branch and enabling it for all PRs. This will enable Github actions for all PRs including those that are based on branches other than the `master`.
Ref: https://github.com/linkedin/bluepill/issues/386
\cc @ob

Enabling github workflows to run tests on all PRs

---

.github/workflows/CI-release.yml

ref https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#macos-1015

Remove install cocoapods step since cocoapods is pre-installed

---

bluepill/src/BPPacker.h
bluepill/src/BPPacker.m
bluepill/src/BPRunner.h
bluepill/src/BPRunner.m
bluepill/tests/BPPackerTests.m
bp/src/BPUtils.h
bp/src/BPUtils.m

Often test bundles that take too long to execute become long pole or bottleneck holding up the Bluepill completion for longer than what is ideally needed. So, splitting the test bundles based on the time estimates of all tests in each split could increase the concurrency, re-gain the lost concurrency opportunities and complete the testing as quickly as possible.
The splitting strategy here is to make sure no single bundle takes longer than `the time taken by all bundles divided by the maximum number of concurrent simulators allowed`.
Please review. \cc @ob, @chenxiao0228

Splitting test bundles based on estimates test execution times

---

bp/src/BPSimulator.m

Fixing a bug where the simulator preferences file was not being passed in the clone simulator code path. \cc @rahul-malik @ob

[ISSUE-384] Pass simulator preferences file when clone simulator feature is enabled

---

bptestrunner/bluepill_batch_test.bzl

If the test or app host is in subfolders, we are not able to find the generated zip/ipa files. Using short_path instead of basename would resolve the issue.

Supporting tests and app hosts in subfolders

---

.github/workflows/PR.yml
.github/workflows/master.yml
.github/workflows/release.yml
README.md
bluepill/tests/BPIntegrationTests.m
bp/src/BPConstants.h

Since Xcode 11.3 is packed with SDK 13.2, we need another constant to
indicate base SDK.

Xcode 11.3 support

---

bptestrunner/bluepill_batch_test.bzl

If the test or app host is in subfolders, we are not able to find the generated zip/ipa files. Using short_path instead of basename would resolve the issue.

Supporting tests and app hosts in subfolders (#419)

---

BPSampleApp/BPSampleAppHangingTests/BPSampleAppHangingTests.m
README.md
bluepill/tests/BPPackerTests.m
bp/bp.xcodeproj/xcshareddata/xcschemes/bp-tests.xcscheme
bp/src/BPConfiguration.h
bp/src/BPConfiguration.m
bp/src/BPExitStatus.h
bp/src/BPExitStatus.m
bp/src/BPSimulator.m
bp/src/BPStats.m
bp/src/BPUtils.m
bp/src/Bluepill.m
bp/src/SimulatorMonitor.m
bp/tests/BPUtilsTests.m
bp/tests/BluepillTests.m
bp/tests/Resource Files/hanging_tests.xml

When a test times out, fails, crashes the app or successfully passes the bundle exits with an appropriate exit status. Often times, one or more tests in the bundle can exhibit one or more of these behaviors in one single execution of a test bundle.  However, the testing of this part of Bluepill's logic is limited right now partially because the combinations are exponential. Another reason is the lack of an easy-to-use mechanism to reproduce/mock different scenarios.
This PR is an attempt to add that ability along with a bunch of new tests and fix any bugs discovered.
With the new ability to test multiple cascading failure scenarios, a few more tests were added to uncover some known issues in exit status.
1. Bluepill tries to merge exit statuses with a `|` operator but since the exit …

Added a few more tests to mock test failure scenarios and fixed a few final Exit Status issues 

---

BPSampleApp/BPSampleAppHangingTests/BPSampleAppHangingTests.m
README.md
bluepill/tests/BPPackerTests.m
bp/bp.xcodeproj/xcshareddata/xcschemes/bp-tests.xcscheme
bp/src/BPConfiguration.h
bp/src/BPConfiguration.m
bp/src/BPExitStatus.h
bp/src/BPExitStatus.m
bp/src/BPSimulator.m
bp/src/BPStats.m
bp/src/BPUtils.m
bp/src/Bluepill.m
bp/src/SimulatorMonitor.m
bp/tests/BPUtilsTests.m
bp/tests/BluepillTests.m
bp/tests/Resource Files/hanging_tests.xml

This PR is to merge the exit code fixes/improvements from https://github.com/linkedin/bluepill/pull/432 and https://github.com/linkedin/bluepill/pull/430 in to `xcode-11.2` branch with Xcode 11.2 support.
\cc @ob @oliverhu @chenxiao0228 @RainNapper

Merge exit code fixes from PR#432 and PR#430 to Xcode 11.2 branch

---

bluepill/src/BPRunner.m
bp/src/BPConfiguration.h
bp/src/BPConfiguration.m
bp/src/BPXCTestFile.h
bp/src/BPXCTestFile.m
bp/src/SimulatorHelper.m

This is a sibling diff to facebook/buck#2346. It allows Bluepill to ingest a list of dependencies from:
- the `DependentProductPaths ` field in the `xctestrun` files, or 
- the `dependencies` key in the test plan file.
At Dropbox, to test correct inter-op with third party applications, our UI tests have a secondary "sidecar" app. During the UI testing, they need to be built and installed together with the main app. The Xcode's default test runner is able to take care of this, as long as the the generated test configuration contains the `testApplicationDependencies`.
Tested this with our apps - the sidecar app installs correctly and tests pass! 🎉

Support sidecar applications

---

.github/workflows/PR.yml
.github/workflows/master.yml
.github/workflows/release.yml
README.md
bp/src/BPConstants.h

The `xcode-11.4` branch was created prematurely. This PR is to merge the https://github.com/linkedin/bluepill/pull/446 or https://github.com/linkedin/bluepill/commit/b3efb790c4899462f5d91f2c7f5eeca5291dae96 into the `xcode-11.4` branch.

Xcode 11.4 support (#446)

---

bluepill/tests/BPIntegrationTests.m
bp/src/SimulatorMonitor.m
bp/tests/BluepillTests.m
bp/tests/Resource Files/crash_tests_with_retry_attempt_2.xml

Implementing the behavior proposed in https://github.com/linkedin/bluepill/issues/423. 
\cc @ob

Feature - Do not retry crashed tests

---

bp/src/SimulatorHelper.m

App will crash if this dylib does not exist in the host app bundle. This dylib is not required for tests to run.

Only reference libXCTestBundleInject.dylib if it exists

---

bluepill/src/BPReportCollector.m
bptestrunner/bluepill_batch_test.bzl
bptestrunner/bluepill_batch_test_runner.template.sh

Change `test_plan_file.basename` to `test_plan_file.short_path`, then modify the runner script template to pass only the basename to the bluepill executable, similar to what is done with BP_CONFIG_FILE here: https://github.com/linkedin/bluepill/blob/master/bptestrunner/bluepill_batch_test_runner.template.sh#L53

Update bazel build script and bazel rule

---

bluepill/src/BPReportCollector.m

We noticed that when we run our XCUITests with bluepill, we need to pass in `NSXMLDocumentTidyXML` as an option when generating the XML results, since Apple's XCUITest output includes some illegal characters, such as "_&quot;_"; below:
t =    47.17s Find: Elements matching predicate &#x27;&quot;create_channel_privacy_switch&quot; IN identifiers&#x27;
Apple's XCUITest framework prints these characters, and as far as I know, there isn't a way to control the verbosity level of XCUITest output logs. 
Per Apple's documentation here: 
https://developer.apple.com/documentation/foundation/nsxmldocument/1413086-initwithdata
"If you specify NSXMLDocumentTidyXML as one of the options, NSXMLDocument performs several clean-up operations on the document XML (such as removing leading tabs). It does …

Add NSXMLDocumentTidyXML as option to NSXMLDocument

---

bluepill/src/main.m
bluepill/tests/BPCLITests.m
bluepill/tests/BPIntegrationTests.m
bluepill/tests/BPPackerTests.m
bluepill/tests/BPRunnerTests.m
bp/src/BPConfiguration.h
bp/src/BPConfiguration.m
bp/src/main.m
bp/tests/BPCLITests.m
bp/tests/BPConfigurationTests.m
bp/tests/BPIntTestCase.m
bp/tests/BPTreeParserTests.m
bp/tests/BPUtilsTests.m

`BP_MASTER` -> `BLUEPILL_BINARY`
`BP_SLAVE` -> `BP_BINARY`
Build Succeeds locally:
```
RegisterExecutionPolicyException /Users/smuthu/Sandbox/bluepill/build/Build/Products/Release/bluepill (in target 'bluepill' from project 'bluepill')
cd /Users/smuthu/Sandbox/bluepill/bluepill
builtin-RegisterExecutionPolicyException /Users/smuthu/Sandbox/bluepill/build/Build/Products/Release/bluepill
** BUILD SUCCEEDED **
Release in build/Bluepill-v5.6.0-2-gabe80d2.zip
precmd: command not found: vcs_info 
```
However there are test failures (although they mirror the failures in master):
```
Failing tests:
bp-tests:
-[BPUtilsTests testNormalizingConfigurationDoesntExcludeTestSuiteWithSimilarPrefix]
-[BPUtilsTests testNormalizingConfigurationOnlyIncludesTestsInIncludedTestSuite]
-[BluepillTests …
```

Replaced BP_MASTER and BP_SLAVE with inclusive terminology

---

bluepill/bluepill.xcodeproj/project.pbxproj
bluepill/src/BPRunner.h
bluepill/src/BPRunner.m
bluepill/src/BPSwimlane.h
bluepill/src/BPSwimlane.m
bluepill/tests/BPIntegrationTests.m
bp/src/BPStats.m

**Issue:**
When a BP is reused, the id increases by 1 automatically, like BP-1 & BP-5. In the trace-profile, the stats will be listed in 2 separated lines, which is not friendly to check.
**Logic Changes:**
Introduce BPSwimlane. Moved all NSTask-related code into BPSwimlane. BPSwimlane is in charge of launching tasks to run test bundles.
BPSwimlane holds LaneID which keeps the same when reused, so the logs are in one lane in tracing-profile.
**Trace-profile Changes:**
Logs of reused BPSwimlane are listed in the same line.
Thread-name: "BP-[THREAD_ID]" -> "BP Swimlane #[LANE_ID]"
Event-name: "bp ([PROCESS_ID])" -> "BP-[THREAD_ID] ([PROCESS_ID])"

Introduce BPSwimlane holding LaneID that keeps the same when reused to fix trace-profile issue.

---

bluepill/bluepill.xcodeproj/project.pbxproj
bluepill/src/BPRunner.h
bluepill/src/BPRunner.m
bluepill/src/BPSwimlane.h
bluepill/src/BPSwimlane.m
bluepill/tests/BPIntegrationTests.m
bp/src/BPStats.m

Moved all NSTask-related code into BPSwimlane.
BPSwimlane is in charge of launching tasks to run test bundles.
BPSwimlane holds LaneID which keeps the same when reused, so the logs are in one lane in tracing-profile.
---
Same with the [PR to master.](https://github.com/linkedin/bluepill/pull/486)

Introduce BPSwimlane holding LaneID that keeps the same when reused.

---

bp/src/BPSimulator.m
bp/src/BPTestBundleConnection.h
bp/src/BPTestBundleConnection.m
bp/src/BPTestDaemonConnection.h
bp/src/BPTestDaemonConnection.m
bp/src/BPXCTestFile.m
bp/src/Bluepill.m

This is a small clean-up so that #491 is smaller.
It just removes some unnecessary imports, and replaces a call to `popen()` with `NSTask`

Small cleanups pre 12.5

---

BPSampleApp/BPSampleApp.xcodeproj/project.pbxproj
BPSampleApp/BPSampleApp.xcodeproj/xcshareddata/xcschemes/BPSampleApp.xcscheme
BPSampleApp/BPSampleAppTests/BPSampleAppNewTests.m
bluepill/src/BPPacker.m
bluepill/tests/BPPackerTests.m
bp/bp.xcodeproj/project.pbxproj
bp/tests/BPTestHelper.h
bp/tests/BPTestHelper.m

Fixing https://github.com/MobileNativeFoundation/bluepill/issues/511 by choosing to pack tests by test count if and when test estimates are missing or adding up to be zero.
\cc @ob @chenxiao0228

Bugfix: Pack tests by test count if test estimates are missing or adding up to be zero

---

.github/workflows/PR.yml
.github/workflows/master.yml
.github/workflows/release.yml
Configurations/common.xcconfig
README.md
bp/bp.xcodeproj/project.pbxproj
bp/src/BPConstants.h
bp/src/BPUtils.m
bp/tests/BPReportTests.m
bp/tests/Resource Files/fatal_tests_attempt_3.xml

Just an attempt to add Xcode 13 support ¯\_(ツ)_/¯

Add Xcode 13 support

---

bluepill/bluepill.xcodeproj/project.pbxproj
bluepill/src/BPReportCollector.m
bluepill/tests/BPReportCollectorTests.m
bluepill/tests/Resource Files/Expected-TEST-FinalReport-for-invalid-xml.xml
bluepill/tests/simulator-invalid-xml/1/result1-1.xml
bluepill/tests/simulator-invalid-xml/1/result1-2.xml
bluepill/tests/simulator-invalid-xml/2/result2-1.xml
bluepill/tests/simulator-invalid-xml/2/result2-2.xml
bluepill/tests/simulator-invalid-xml/2/result2-3.xml
bluepill/tests/simulator-invalid-xml/3/result3.xml
bluepill/tests/simulator-invalid-xml/4/result4.xml

Presently, when parsing an XML result file fails, all subsequent reports are skipped because the `NSError` instance is being reused. This PR fixes that issue and adds a test case.

When parsing an XML result file fails, don't fail while merging subsequent test results

---

.github/workflows/master.yml
.github/workflows/release.yml

A couple of minor fixes so that the checks on main branch and releases use the appropriate Xcode version.
\cc @ob

Fix the workflows of main branch and releases

---

bptestrunner/bluepill_batch_test.bzl

In the previous was we would `rstrip` the test_host's app extension. If this happened to be the same as the end of the app name it would strip that too.
For example if it was `Foo-App.app` it would change to `Foo-A.app`.
This updates to take whatever is before the app extension by splitting the test_host's extension + '.' and taking the first entry.
This fixes https://github.com/MobileNativeFoundation/bluepill/issues/528

Fix how the test host app is made into a .app

---

Bluepill.podspec

tvOS and watchOS sdks and their simulators are not installed by default
with Xcode 14. So specifying osx and ios to workaround them.
This podspec is mean to bring in the binaries to Pods folder so other tools
are able to use it. It does not build or mean to be consumed as a library

Specify platform to exclude tvOS, watchOS

---

Bluepill.podspec

tvOS and watchOS sdks and their simulators are not installed by default
with Xcode 14. So specifying osx and ios to workaround them.
This podspec is mean to bring in the binaries to Pods folder so other tools
are able to use it. It does not build or mean to be consumed as a library

Specify platform to exclude tvOS, watchOS (#541)

---

bp/src/BPTMDRunnerConnection.m

This should fix https://github.com/MobileNativeFoundation/bluepill/issues/533
Root cause: A XCTFuture object with "requesting ready for testing" couldn't get fulfilled and timed out because we did not start the test plan at the right time. 
Fix is to make sure to wait for the test bundle being actually connected with capabilities, and then we fire the trigger to start the test plan.
We have tested this fix internally at LinkedIn and it's working properly.

Trigger the test when the bundle is actually connected

---

bptestrunner/bluepill_batch_test_runner.template.sh

Currently when running bluepill from bazel, `$TEST_UNDECLARED_OUTPUTS_DIR` is not accessible from test runtime by passing with `--test_env`
Supporting it by expanding the variable in the shell script and passing it to the test plan. 
So we can run something like `bazel test Taget --config Debug --test_env SCREENSHOT_DIR=\$TEST_UNDECLARED_OUTPUTS_DIR/screenshots`. Then the screenshot can be saved to the undeclared outputs dir and be packaged to the final `bazel-testlog` folder
ref: https://bazel.build/reference/test-encyclopedia#initial-conditions

Expand $TEST_UNDECLARED_OUTPUTS_DIR  when running test from bazel

---

bp/src/BPSimulator.h
bp/src/BPSimulator.m

We were seeing lots of test timeout issues on macOS Ventura machines. It turned out that there's some shutdown error for simulators causing hanging bp processes. See below log for example:
```
{24164} 20230825.132813 [  ERROR ] (BP-1) Timeout: [Attempt 1] Create Simulator
{24164} 20230825.132813 [  ERROR ] (BP-1) The operation couldnâ€™t be completed. (org.linkedin.bluepill.ErrorDomain error -1.)
{24164} 20230825.132813 [  INFO  ] (BP-1) Relaunching the simulator due to a BAD STATE
{24164} 20230825.132813 [  INFO  ] (BP-1) [Attempt 1] Delete Simulator
{24164} 20230825.132813 [  INFO  ] (BP-1) Shutting down Simulator
{24164} 20230825.132859 [  INFO  ] (BP-1) Simulator 0F53DAFD-72C0-4B9C-8DA0-6975202DBB28 achieved the BOOTED state Booted
{24164} 20230825.132900 [  INFO  ] (BP-1) Completed: …
```

Proper shutdown mechanism

---

bp/src/BPSimulator.m

The bluepill test was hanging and causing timeout during GHA.
Investigated and figured out the issue being one of the `shutdownSimulatorWithError:` call should pass in a `simDevice` explicitly.
Let's see if the tests are going to pass

Pass simDevice to the shutdown method

---

.github/workflows/PR.yml
.github/workflows/master.yml
.github/workflows/release.yml
bluepill/bluepill.xcodeproj/project.pbxproj
bp/bp.xcodeproj/project.pbxproj
bp/src/BPConfiguration.h
bp/src/BPConfiguration.m
bp/src/BPConstants.h
bp/src/BPSimulator.m
bp/src/BPTMDControlConnection.m
bp/src/BPTMDRunnerConnection.h
bp/src/BPTMDRunnerConnection.m
bp/src/Bluepill.m
bp/src/PrivateHeaders/CoreSimulator/SimDeviceBootInfo.h
bp/tests/BPReportTests.m
bp/tests/BluepillTests.m
bp/tests/Resource Files/simulator-preferences.plist
scripts/bluepill.sh

Support Xcode 15.1
- Since Xcode 15, the simulator eats up more machine resources. So made sure we boot and delete the simulators correctly with better status check
- Increased test bundle connection timeout to address the performance issue
- There are cases where a test bundle disconnects but bp keeps waiting to check for some output. Added a timeout config (`testBundleDisconnectTimeout`) to address that
- Made sure to call new private delegate functions 
- Added a new test batch to account for slower test run in Xcode 15.

Xcode 15.1
